Partially completion
babeanu-dorian/AssetShare pull request #19
Opened 2020-04-04 11:55 UTC by babeanu-dorian

Added functionality:
 - buy-offers publication (with or without an intended seller)
 - buy or sell only a portion of the shares in an offer
 - autocomplete offers (combine a sell-offer with multiple buy-offers, or vice-versa) and get the best deal available (this requires multiple transactions / signings)

UI changes:
 - added table for active buy-offers, and a tab to switch between sell-offers and buy-offers
 - added button for publishing buy-offers
 - the input field "price" in the Offers section now expects the cost in ETH of one percentage (1%) of shares (floating point numbers are accepted)
 - displayed offers now have a text field that allows users to input the amount of shares they want to sell/buy from an offer
 - the displayed offer price now updates based on the selected amount of shares
 - added check-box for turning offer-autocompletion-upon-publishing on or off
 - displayed offers now have a button that alows their owners to autocomplete them

2020-04-07 13:09 UTC, Kloppie5 commented on app/src/script.js
> +                case 'SHARES_TRANSFERED':
TRANSFERRED*

2020-04-07 13:12 UTC, Kloppie5 requested changes
Please check that things are spelled correctly

2020-04-07 13:37 UTC, babeanu-dorian commented on app/src/script.js
> +                case 'SHARES_TRANSFERED':
fixed

2020-04-08 15:40 UTC, Kloppie5 approved these changes

2020-04-08 15:40 UTC, merged